### ISSUE TITLE
Activity level

### ISSUE THREAD

**Issue by kailuowang** [fosskers/scalaz-and-cats#6]
In regards to project activity, I would argue that Cats is **significantly more** active. 
I have two reasons to believe that: 
1. Cats, as a much younger project, now has 183 contributors, vs 157 contributors for Scalaz
2. You used prev month commits as a metric, but Cats is mostly doing squash PR merge, meaning for most PRs merged we have only 1 commit/PR while Scalaz might have more than one commits per PR. If you look at the PR merged here is the data:

| month        | Cats           | ScalaZ |
| ------------- |-------------:| -----:|
| Last 30 days    | 32 | 16 |
| Oct   | 43      |   11 |
| Sept | 42     |    14 |

*My count might be 1 to 2 off. But the ratio between the two should be roughly the same.

**Comment by fosskers** [comment]
I hadn't realized until I did [this PR](https://github.com/typelevel/cats/pull/2056) that you guys do squash merges. I'll admit that that should change the way we perceive activity.

**Comment by ashawley** [comment]
I was expecting something similar with respect to project activity by highlighting the release activity.

I've collected some of that data to help get it going.

Release        |Year
---------------|----
Scalaz 6.0     |2011
Scalaz 7.0     |2012
Scalaz 7.1     |2014
Scalaz 7.2     |2015
eff  1.0       |2016
cats 0.6       |2016
cats 0.7       |2016
cats 0.8       |2016
eff  2.0       |2016
cats 0.9       |2017
eff  3.0       |2017
eff  4.0       |2017
cats-effect 0.3|2017
cats-effect 0.4|2017
cats 1.0       |2017
cats-effect 0.5|2017
eff  5.0       |2017

I'm unsure of whether Typelevel packages like cats-mtl, fs2, mouse and so on should be included.

**Comment by fosskers** [comment]
Some aggregate numbers may be more digestable for users. "Release frequency" or something, perhaps rendered with a chart.

**Comment by kailuowang** [comment]
I am going to close this issue since there isn't much point of keeping it open.

**Comment by fosskers** [comment]
After thinking about it again, activity level is hard to measure (or qualify) and might not be useful. Project activity is correlated to project health/quality, but strictly does not cause it. So, I'm okay with this issue being closed.
