### ISSUE TITLE
codes of conduct

### ISSUE THREAD

**Issue by SethTisue** [fosskers/scalaz-and-cats#7]
is it intentional that code-of-conduct type issues aren't even mentioned?

I can see that it wouldn't be appropriate to recapitulate the entire history of the split in this repo...

...but it seems odd to me not to even mention the different ways that the two projects are governed

**Comment by fosskers** [comment]
As you guessed, I have on purpose not touched on political issues at all. In my personal experience, contributors to both libraries have been friendly, intelligent, and open to discussion.

I really, *really* don't want to dwell on the past with this comparison repo.

**Comment by SethTisue** [comment]
Things this definitely wouldn't need to be about:

* How the current situation was arrived at
* The personal qualities of the individuals involved

I did not mean to suggest dwelling on the past, or even covering the history _at all_.

I do mean to suggest there an important difference between the projects _today, now_ that is important to many prospective users and contributors, even ones with zero interest in delving into how the current situation came about.

Do you as like, of course! I'm just trying to clarify what the suggestion even is.

**Comment by fosskers** [comment]
Thanks, that's appreciated. I'm going to think on this more.

**Comment by fosskers** [comment]
Closing this after all, as I've experienced no conduct related issues with either community. For the purpose of this comparison repo at least - which is focused on the question of which library to use, not to join as a dev -  I don't think touching on official codes of conduct is necessary.
